name: Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [18, 20, 22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
      - run: pnpm i
      - run: pnpm build
      - run: pnpm demo